title: ABbites - Nutrition Tracker for College Campuses
description: A full-stack nutrition tracking app for college students
theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0

plugins:
  - jekyll-remote-theme

# Optional variables
show_downloads: false
